services:

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - social
    volumes:
      - ./rabbitmq/rabbit_data/:/var/lib/rabbitmq/
      - ./rabbitmq/rabbit_log/:/var/log/rabbitmq/
    restart: on-failure  

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
    
    networks:
      - social
    depends_on:
      - rabbitmq

  worker:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - ./core:/app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      
    depends_on:
      - rabbitmq
      - django
    restart: on-failure
    
    networks:
      - social

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '8080:80'
      - '25:25'
      - '143:143'
    volumes:
        - smtp4dev-data:/smtp4dev
    environment:

    - ServerOptions__Urls=http://*:80
    - ServerOptions__HostName=smtp4dev
    networks:
      - social

volumes:
  smtp4dev-data:


networks:
  social:
    name: social
    driver: bridge